# Generated by Django 3.2.22 on 2023-11-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_salesstatistics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesStatistics',
        ),
    ]
