# Generated by Django 3.2.22 on 2023-11-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brushes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brush',
            options={'verbose_name_plural': 'Brushes'},
        ),
        migrations.AlterModelOptions(
            name='brushcategory',
            options={'verbose_name_plural': 'Brush Categories'},
        ),
        migrations.AddField(
            model_name='brush',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brush',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
