# Generated by Django 3.2.22 on 2023-11-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brushes', '0004_brushbundle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrushBundle',
        ),
    ]
